#include <memcached_rb.h>
#include <memcached_rb_behavior.h>

const char *MEMCACHED_BEHAVIOR_NAMES[] = {
  "MEMCACHED_BEHAVIOR_NO_BLOCK",
  "MEMCACHED_BEHAVIOR_TCP_NODELAY",
  "MEMCACHED_BEHAVIOR_HASH",
  "MEMCACHED_BEHAVIOR_KETAMA",
  "MEMCACHED_BEHAVIOR_SOCKET_SEND_SIZE",
  "MEMCACHED_BEHAVIOR_SOCKET_RECV_SIZE",
  "MEMCACHED_BEHAVIOR_CACHE_LOOKUPS",
  "MEMCACHED_BEHAVIOR_SUPPORT_CAS",
  "MEMCACHED_BEHAVIOR_POLL_TIMEOUT",
  "MEMCACHED_BEHAVIOR_DISTRIBUTION",
  "MEMCACHED_BEHAVIOR_BUFFER_REQUESTS",
  "MEMCACHED_BEHAVIOR_USER_DATA",
  "MEMCACHED_BEHAVIOR_SORT_HOSTS",
  "MEMCACHED_BEHAVIOR_VERIFY_KEY",
  "MEMCACHED_BEHAVIOR_CONNECT_TIMEOUT",
  "MEMCACHED_BEHAVIOR_RETRY_TIMEOUT",
  "MEMCACHED_BEHAVIOR_KETAMA_WEIGHTED",
  "MEMCACHED_BEHAVIOR_KETAMA_HASH",
  "MEMCACHED_BEHAVIOR_BINARY_PROTOCOL",
  "MEMCACHED_BEHAVIOR_SND_TIMEOUT",
  "MEMCACHED_BEHAVIOR_RCV_TIMEOUT",
  "MEMCACHED_BEHAVIOR_SERVER_FAILURE_LIMIT",
  "MEMCACHED_BEHAVIOR_IO_MSG_WATERMARK",
  "MEMCACHED_BEHAVIOR_IO_BYTES_WATERMARK",
  "MEMCACHED_BEHAVIOR_IO_KEY_PREFETCH",
  "MEMCACHED_BEHAVIOR_HASH_WITH_PREFIX_KEY",
  "MEMCACHED_BEHAVIOR_NOREPLY",
  "MEMCACHED_BEHAVIOR_USE_UDP",
  "MEMCACHED_BEHAVIOR_AUTO_EJECT_HOSTS",
  "MEMCACHED_BEHAVIOR_NUMBER_OF_REPLICAS",
  "MEMCACHED_BEHAVIOR_RANDOMIZE_REPLICA_READ",
  "MEMCACHED_BEHAVIOR_CORK",
  "MEMCACHED_BEHAVIOR_TCP_KEEPALIVE",
  "MEMCACHED_BEHAVIOR_TCP_KEEPIDLE",
  "MEMCACHED_BEHAVIOR_LOAD_FROM_FILE",
  "MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS",
  "MEMCACHED_BEHAVIOR_DEAD_TIMEOUT",
  "MEMCACHED_BEHAVIOR_SERVER_TIMEOUT_LIMIT",
  "MEMCACHED_BEHAVIOR_MAX"
};
#define MEMCACHED_BEHAVIORS_COUNT 39

const char* MEMCACHED_HASH_NAMES[] = {
  "MEMCACHED_HASH_DEFAULT",
  "MEMCACHED_HASH_MD5",
  "MEMCACHED_HASH_CRC",
  "MEMCACHED_HASH_FNV1_64",
  "MEMCACHED_HASH_FNV1A_64",
  "MEMCACHED_HASH_FNV1_32",
  "MEMCACHED_HASH_FNV1A_32",
  "MEMCACHED_HASH_HSIEH",
  "MEMCACHED_HASH_MURMUR",
  "MEMCACHED_HASH_JENKINS",
  "MEMCACHED_HASH_MURMUR3",
  "MEMCACHED_HASH_CUSTOM",
  "MEMCACHED_HASH_MAX",
};
#define MEMCACHED_HASH_COUNT 13

const char* MEMCACHED_DISTRIBUTION_NAMES[] = {
  "MEMCACHED_DISTRIBUTION_MODULA",
  "MEMCACHED_DISTRIBUTION_CONSISTENT",
  "MEMCACHED_DISTRIBUTION_CONSISTENT_KETAMA",
  "MEMCACHED_DISTRIBUTION_RANDOM",
  "MEMCACHED_DISTRIBUTION_CONSISTENT_KETAMA_SPY",
  "MEMCACHED_DISTRIBUTION_CONSISTENT_WEIGHTED",
  "MEMCACHED_DISTRIBUTION_VIRTUAL_BUCKET",
  "MEMCACHED_DISTRIBUTION_CONSISTENT_MAX"
};
#define MEMCACHED_DISTRIBUTION_COUNT 8

VALUE
rb_connection_set_behavior(VALUE self, VALUE rb_behavior, VALUE rb_value)
{
  memcached_return_t rc;
  memcached_ctx *ctx = get_ctx(self);

  uint64_t data = 0;

  switch (TYPE(rb_value)) {
  case T_TRUE:
  case T_STRING:
    // TODO try to lookup constant
    data = 1;
    break;
  case T_FIXNUM:
    data = FIX2UINT(rb_value);
  case T_NIL:
  case T_FALSE:
  default:
    break;
  }

  rc = memcached_behavior_set(ctx->memc, NUM2UINT(rb_behavior), data);
  handle_memcached_return(rc);
  return (rc == MEMCACHED_SUCCESS);
}

void
Init_memcached_rb_behavior(void)
{
  int i;
  VALUE rb_mBehaviors = rb_define_module_under(rb_mMemcached, "Behaviors");

  for(i = 0; i < MEMCACHED_BEHAVIORS_COUNT; i++) {
    rb_define_const(rb_mBehaviors, MEMCACHED_BEHAVIOR_NAMES[i], UINT2NUM(i));
  }
  for(i = 0; i < MEMCACHED_HASH_COUNT; i++) {
    rb_define_const(rb_mBehaviors, MEMCACHED_HASH_NAMES[i], UINT2NUM(i));
  }
  for(i = 0; i < MEMCACHED_DISTRIBUTION_COUNT; i++) {
    rb_define_const(rb_mBehaviors, MEMCACHED_DISTRIBUTION_NAMES[i], UINT2NUM(i));
  }
}
